### ISSUE TITLE
No Potion Found when using non-vanilla potion effects

### ISSUE THREAD

**Issue by Lothrazar** [Darkhax-Minecraft/Cravings#6]
In my latest.log it said this

```
[23:01:28] [main/ERROR]: ********************************************************************************
[23:01:28] [main/ERROR]: * No potion found for id cyclicmagic:potion.frostwalker config line:
[23:01:28] [main/ERROR]: * cyclicmagic:potion.frostwalker, 6000
[23:01:28] [main/ERROR]: ********************************************************************************
[23:01:28] [main/ERROR]: ********************************************************************************
[23:01:28] [main/ERROR]: * No potion found for id cyclicmagic:potion.waterwalk config line:
[23:01:28] [main/ERROR]: * cyclicmagic:potion.waterwalk, 6000
[23:01:28] [main/ERROR]: ********************************************************************************
[23:01:28] [main/INFO]: Building list of food items.
[23:01:28] [main/INFO]: Food list built. 70 items found. Took 4ms
[23:01:28] [main/WARN]: ****************************************
[23:01:28] [main/WARN]: * Dangerous alternative prefix `minecraft` for name `random`, expected `cravings` invalid registry invocation/invalid name?
[23:01:28] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
[23:01:28] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
[23:01:28] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:66)
[23:01:28] [main/WARN]: *  at net.darkhax.bookshelf.lib.WeightedSelectorRegistry.addEntry(WeightedSelectorRegistry.java:40)
[23:01:28] [main/WARN]: *  at net.darkhax.cravings.Cravings.preInit(Cravings.java:58)
[23:01:28] [main/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[23:01:28] [main/WARN]: ****************************************
[23:01:30] [main/WARN]: Skipping bad option: lastServer:
```

My config file is here
https://pastebin.com/5hQLY39U

I just register the potions in with the normal registry event https://github.com/PrinceOfAmber/Cyclic/blob/eb886e0de62c84952b7ba80de6fa82f6b9c96515/src/main/java/com/lothrazar/cyclicmagic/registry/PotionEffectRegistry.java#L61

And a screenshot showing the id is valid

![crav](https://user-images.githubusercontent.com/621529/33872017-e81f127c-dec9-11e7-9c4c-badf11f0e370.PNG)

**Comment by Darkhax** [comment]
Thanks for the report. The issue here is that the modded potions are being registered before my config file is loaded. I need to shift that back a bit.

**Comment by Darkhax** [comment]
Thanks again for the report. I believe this was fixed in the latest version, if not let me know :p

**Comment by Darkhax** [comment]
https://minecraft.curseforge.com/projects/cravings/files/2509860
